on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  
jobs:
  evil:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        pwd
        ls -ltr
        nmcli
